version: "3.9"

services:
  app:
    container_name: "app_container"
    image: "app:1.0"
    env_file:
      - .env
    build:
      context: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/app
    command: >
      sh -c "npm start"
    environment:
      - MONGODB_CONNSTRING=mongodb://db
    depends_on:
      - db

  db:
    container_name: "db_container"
    image: mongo:5.0
    ports:
      - "${DB_PORT}:27017"
    env_file:
      - .env
    volumes:
      - db-data:/data/db

volumes:
  db-data:
